name: Git Secrets Vulnerability
on:
  push:
    branches:
      - master
jobs:
  Git-Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Master Checkout
        uses: actions/checkout@v2
        with:
          repository: rutvi126/Git-Secrets-Vulnerability
          path: dum

      - name: Configure Chronicle Credentials
        env:
            DUMMY_CREDS: ${{secrets.DUMMY_CREDS}}
            REF: ${{ github.ref }}
        run: |
          echo "${GITHUB_WORKSPACE}"
          echo "${DUMMY_CREDS} | jq -r" > ${GITHUB_WORKSPACE}/dum/creds.json
          cd "${GITHUB_WORKSPACE}/dum
          python3 show_creds.py


              
